# Yarn v4 (Berry) 設定ファイル
# 詳細: https://yarnpkg.com/configuration/yarnrc

# Node.js のリンクモード（node-modules または pnp）
nodeLinker: node-modules

# パフォーマンス設定
enableGlobalCache: true
enableImmutableInstalls: false

# セキュリティとテレメトリ
enableScripts: true
enableTelemetry: false

# ログフィルター（不要な警告を非表示）
logFilters:
  - code: YN0002  # Package doesn't seem to be meant for consumers
    level: discard
  - code: YN0060  # Incompatible peer dependency
    level: discard

# TypeScript サポート（オプション）
# プロジェクトで TypeScript を使用する場合は以下のプラグインを有効化
# plugins:
#   - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
#     spec: "@yarnpkg/plugin-typescript"Berry) 用の基本的な .yarnrc.yml サンプル
nodeLinker: node-modules

# キャッシュディレクトリの指定（任意）
# cacheFolder: .yarn/cache

# プラグインの自動インストールを有効化（任意）
# enableGlobalCache: true

# npm レジストリの指定（必要に応じて）
# npmRegistryServer: "https://registry.npmjs.org"

# scripts の postinstall などで node_modules/.bin を使う場合
# binFolder: "./node_modules/.bin"
